# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='main_image',
        ),
    ]
