# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindex',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogIndex',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
